# Generated by Django 5.2.6 on 2025-09-13 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wbapp', '0002_record_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='last_name',
        ),
    ]
