# Generated by Django 5.2.6 on 2025-09-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbapp', '0003_rename_first_name_record_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='last_payment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
