# Generated by Django 5.2.6 on 2025-09-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbapp', '0004_record_last_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
