# Generated by Django 5.2.6 on 2025-09-16 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wbapp', '0005_record_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='is_active',
        ),
    ]
