# Generated by Django 5.2.6 on 2025-09-16 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbapp', '0006_remove_record_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='last_payment',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
