# Generated by Django 5.2.6 on 2025-09-16 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wbapp', '0008_alter_record_last_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='last_payment',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
